name: air_quality_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  
  # Dependencias existentes
  http: ^1.2.1
  flutter_map: ^7.0.1
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  flutter_local_notifications: ^17.2.1
  url_launcher: ^6.3.0
  fl_chart: ^0.68.0

  # --- NUEVAS DEPENDENCIAS ---
  shared_preferences: ^2.2.3 # Para recordar la pantalla de bienvenida
  provider: ^6.1.2             # Para la gestión de estado
  permission_handler: ^11.0.0 # Para abrir la configuración de la app
  flutter_map_cancellable_tile_provider: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  rename_app: ^1.3.1

rename_app:
  name: "Aeris"


flutter:
  uses-material-design: true

  
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product Sans Regular.ttf
        - asset: assets/fonts/Product Sans Bold.ttf
          weight: 700